server.port: ${PORT:${SERVER_PORT:0}}
server.error.include-message: always

custom:
  health:
    status: UP
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_social?useSSL=false&serverTimeZone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initializationFailTimeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  api-docs:
    enabled: true
    path: /api/v1/social/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/v1/social/doc/swagger-ui.html

  packages-to-scan: com.digitalholics
  paths-to-match: /api/v1/social/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,refresh,customhealth,info"
